### PR TITLE
Add browser compatibility by making "os" dependency optional — fixes #6

### LINKED ISSUE #6: Browser compatibility
This module is used in `p-*` modules which should support being run in browsers. Would it be possible to make the dependency on `os` optional?

See https://github.com/sindresorhus/is-reachable/issues/18

### PR DESCRIPTION
**Pull request by Jblew**
This pr simply requires "os" only in node environment. Also I've added a basic headless browser test using testcafe. 

Hope you like it!

### CODE REVIEW

**Comment by sindresorhus** [comment]
I’m happy to merge the fix, but I’m not interested in all this boilerplate for browser testing. A better fix would be to use the “browser” field in package to override the “os” dependency with an empty object.

**Comment by Jblew** [comment]
Oh, sorry! I didn't check it well enough and just saw the issue. It looks like webpack is already shimming os.homedir(), so probably there is no need for this PR at all, and we can close the issue too. I do not use other bundlers so I am not sure how browserify and the others handle it. According to https://github.com/defunctzombie/package-browser-field-spec it would be safer to add `browser: { os: false }`. I'll create a PR for that, and I am closing this one. 

PS. I am sorry to mention it here and even more sorry to bother you, but I've just added a [PR](https://github.com/sindresorhus/ow/pull/154) to the `ow` repo for a functionality that I would really love to use just now for the sake of clean code in my projects ;) . It would be really great if you could merge this small change. Of course, I understand if it's not possible right now. (https://github.com/sindresorhus/ow/pull/154) . Thanks!

**Comment by sindresorhus** [comment]
> PS. I am sorry to mention it here and even more sorry to bother you, but I've just added a PR to the ow repo for a functionality that I would really love to use just now for the sake of clean code in my projects ;) . It would be really great if you could merge this small change. Of course, I understand if it's not possible right now. (sindresorhus/ow#154) . Thanks!

I saw it, but I'm on summer vacation now, so my time is limited for the next 3 weeks. I will try to look at it as soon as I can.

**Comment by Jblew** [comment]
I understand, so don't spend time on it, I'll wait. And have a restful vacation! :)

**Pull request closed without merging**
