### PR TITLE
Support Windows

### PR DESCRIPTION
**Pull request by mastilver**
I would like your input on what would be the best solution to fix this issue

### CODE REVIEW

**Comment by sindresorhus** [comment]
I would just do a separate `replace()` beforehand changing all backslashes to forward slashes. Windows supports forward slashes too, but stack traces uses backslashes.

**Comment by mastilver** [comment]
@sindresorhus Is that what you were expecting?

**Comment by SamVerschueren** [comment]
Maybe we should also add [appveyor.yml](https://github.com/sindresorhus/appveyor-node) to this PR? Or do you want to add it in a follow up commit @sindresorhus ?

**Comment by sindresorhus** [comment]
@SamVerschueren Nah. AppVeyor is annoying in so many ways (slow, unreliable, takes long to set up). I usually only add it for larger projects.

**Pull request merged**
