### PR TITLE
correctly remove babel-polyfill paths

### PR DESCRIPTION
**Pull request by mastilver**

### CODE REVIEW

**Comment by sindresorhus** [comment]
I think the regex is getting too complex. Maybe we could dynamically generate it to make it easier to add additional entries in the future?

**Comment by mastilver** [comment]
Yep, i thought the same but wasn't sure if you would agree

**Comment by sindresorhus** [comment]
Would you be willing to do the change?

**Comment by mastilver** [comment]
@sindresorhus What do you think about that?

**Comment by sindresorhus** [comment]
Looks great. Thank you :)

**Pull request merged**
